services:

  codely.mooc_backend.controller.user.put:
    class: CodelyTv\MoocBackend\Controller\User\UserPutController
    parent: codely.mooc_backend.controller
    public: true

  codely.mooc_backend.controller.user.get:
    class: CodelyTv\MoocBackend\Controller\User\UserGetController
    parent: codely.mooc_backend.controller
    public: true
