services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Mooc\Students\Application\:
    resource: '../Application/*'
    exclude: '../Application/{*Command.php, *Query.php}'


  # Infrastructure

  CodelyTv\Mooc\Students\Domain\StudentRepository: '@CodelyTv\Mooc\Students\Infrastructure\Persistence\StudentRepositoryMySql'
  CodelyTv\Mooc\Students\Infrastructure\Persistence\StudentRepositoryMySql:
    autowire: true
    public: true

