version: '3'

services:
    nginx:
        image: nginx:1.15.5-alpine
        container_name: cqrs_codely_tv_nginx
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./etc/infrastructure/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        container_name: cqrs_codely_tv_php
        build:
            context: etc/infrastructure/php
        ports:
            - "2244:22"
            - "9000:9000"
        volumes:
            - "$PWD:/app"
        environment:
            - PHP_IDE_CONFIG=serverName=CodelyCQRSCourse
        depends_on:
            - mysql
        working_dir: "/app"

    mysql:
        image: mysql:5.7.23
        container_name: cqrs_codely_tv_mysql
        ports:
            - "3306:3306"
        env_file:
            - .env