services:
  _defaults:
    autoconfigure: true

  # Subscriber

  codely.mooc.notifications.subscriber.create_notification_on_video_created:
    class: CodelyTv\Mooc\Notifications\Application\Create\CreateNotificationOnVideoCreated
    arguments:
      - '@codely.mooc.notifications.notification_creator'

  codely.mooc.notifications.subscriber.send_notification_on_notification_created:
    class: CodelyTv\Mooc\Notifications\Application\Send\SendStaffNotificationOnNotificationCreated
    arguments:
      - '@codely.mooc.notifications.notification_sender'


  # Services

  codely.mooc.notifications.notification_creator:
    class: CodelyTv\Mooc\Notifications\Application\Create\NotificationCreator
    arguments:
      - '@codely.infrastructure.uuid_generator'
      - '@codely.mooc.domain_event_publisher'

  codely.mooc.notifications.notification_sender:
    class: CodelyTv\Mooc\Notifications\Application\Send\NotificationSender
    arguments:
      - '@codely.mooc.notifications.notifier'
