imports:
  - { resource: config_dev.yml }

parameters:

  test.client.parameters:
    HTTP_HOST:
    HTTP_USER_AGENT:
    HTTP_ACCEPT:
    HTTP_ACCEPT_LANGUAGE:
    HTTP_ACCEPT_CHARSET:
    SERVER_PROTOCOL:
    REQUEST_TIME:

framework:

  test: ~

services:

  codely.mooc.notification.notifier:
    class: CodelyTv\Mooc\Notification\Infrastructure\Notifier\FakeNotifier
