services:

  codely.infrastructure.domain_event_subscribers_configuration:
    class: CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventSubscribersConfiguration

  codely.infrastructure.domain_event_mapping:
    class: CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventMapping
    arguments: [!tagged codely.video.subscriber]

  codely.infrastructure.subscribers_mapping:
    class: CodelyTv\Shared\Infrastructure\Bus\Event\SubscribersMapping

  codely.infrastructure.rabbitmq_connection:
    class: CodelyTv\Shared\Infrastructure\RabbitMQ\RabbitMQConnection
    arguments:
      - '%rabbitmq_connection_parameters%'
      - '@logger'

  codely.infrastructure.rabbitmq_domain_event_consumer:
    class: CodelyTv\Shared\Infrastructure\RabbitMQ\RabbitMQDomainEventConsumer
    arguments:
      - '@codely.infrastructure.rabbitmq_connection'
      - '@codely.infrastructure.domain_event_mapping'
      - '@logger'
