services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Mooc\Notifications\Application\:
    resource: '../Application/*'
    exclude: '../Application/{*Command.php, *Query.php}'


  # Infrastructure

  CodelyTv\Mooc\Notifications\Domain\NotificationRepository: '@CodelyTv\Mooc\Notifications\Infrastructure\Persistence\MySqlNotificationRepository'
  CodelyTv\Mooc\Notifications\Infrastructure\Persistence\MySqlNotificationRepository:
    autowire: true
    public: true

  CodelyTv\Mooc\Notifications\Domain\Notifier: '@CodelyTv\Mooc\Notifications\Infrastructure\Notifier\SlackNotifier'

  CodelyTv\Mooc\Notifications\Infrastructure\Notifier\EmailNotifier:
    arguments:
      - '%video_notification_email_username%'
      - '%video_notification_email_password%'

  CodelyTv\Mooc\Notifications\Infrastructure\Notifier\SlackNotifier:
    arguments:
      - '%slack_video_notification_hook_url%'
      - username: '%slack_video_notification_username%'
        channel: '%slack_video_notification_channel%'
