services:

  codely.mooc.notification.repository:
    class: CodelyTv\Mooc\Notification\Infrastructure\Persistence\MySqlNotificationRepository
    arguments:
      - '@codely.mooc.infrastructure.database'

  codely.mooc.notification.notifier:
    alias: codely.mooc.notification.slack_notifier

  codely.mooc.notification.email_notifier:
    class: CodelyTv\Mooc\Notification\Infrastructure\Notifier\EmailNotifier
    arguments:
      - '%video_notification_email_username%'
      - '%video_notification_email_password%'

  codely.mooc.notification.slack_notifier:
    class: CodelyTv\Mooc\Notification\Infrastructure\Notifier\SlackNotifier
    arguments:
      - '%slack_video_notification_hook_url%'
      - username: '%slack_video_notification_username%'
        channel: '%slack_video_notification_channel%'
