services:

  codely.mooc_backend.controller:
    class: CodelyTv\Shared\Infrastructure\Api\Controller\ApiController
    abstract: true
    arguments:
      - '@codely.mooc.query_bus'
      - '@codely.mooc.command_bus'
      - '@codely.mooc_backend.exception_handler'
