services:

  codely.mooc_backend.subscriber.exception_response:
    class: CodelyTv\Shared\Infrastructure\Api\EventSubscriber\ApiExceptionSubscriber
    arguments:
      - '@fos_rest.view_handler.default'
      - '@codely.mooc_backend.exception_handler'
    tags:
      - { name: kernel.event_subscriber }

  codely.mooc_backend.subscriber.exception_logger:
    class: CodelyTv\Shared\Infrastructure\Api\EventSubscriber\ApiExceptionLoggerSubscriber
    arguments:
      - '@monolog.logger.api'
      - '@codely.mooc_backend.exception_handler'
    tags:
      - { name: kernel.event_subscriber }

  codely.mooc_backend.subscriber.response_view:
    class: CodelyTv\Shared\Infrastructure\Api\EventSubscriber\ApiResponseViewSubscriber
    tags:
      - { name: kernel.event_subscriber }

  codely.mooc_backend.exception_handler:
    class: CodelyTv\Shared\Infrastructure\Api\Exception\ApiExceptionsHttpStatusCodeMapping
