user_put:
  path:     /users/{id}
  defaults: { _controller: codely.mooc_backend.controller.user.put }
  methods:  [PUT]

user_get:
  path:     /users/{id}
  defaults: { _controller: codely.mooc_backend.controller.user.get }
  methods:  [GET]
