services:

  codely.api.controller:
    class: CodelyTv\Shared\Infrastructure\Api\Controller\ApiController
    abstract: true
    arguments:
      - '@codely.video.query_bus'
      - '@codely.video.command_bus'
      - '@codely.api.exception_handler'
