services:

  codely.infrastructure.domain_event_publisher_sync:
    class: CodelyTv\Infrastructure\Bus\Event\DomainEventPublisherSync
    public: false

  codely.infrastructure.domain_event_subscribers_configuration:
    class: CodelyTv\Infrastructure\Bus\Event\DomainEventSubscribersConfiguration

  codely.infrastructure.domain_event_mapping:
    class: CodelyTv\Infrastructure\Bus\Event\DomainEventMapping

  codely.infrastructure.subscribers_mapping:
    class: CodelyTv\Infrastructure\Bus\Event\SubscribersMapping
